Created Discord Documentation
MLH-Fellowship/n8n-docs pull request #1
Opened 2020-06-12 21:29 UTC by erin2722

2020-06-15 12:58 UTC, ivov commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +6. Click on *Exceute Node* to run the workflow. :tada:
Typo: `Exceute`

2020-06-15 13:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Discord]()
Two links missing? But I'm not sure what they should be pointing to. Maybe the first to a future `nodes-library/core-nodes/Start/README.md` and the second to itself? (The latter wouldn't make much sense.)

2020-06-15 18:58 UTC, ivov commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Discord]()
Tanay just confirmed the first link should point to `docs/nodes/nodes-library/core-nodes/Start/README.md` and the second one should _not_ be a link.

2020-06-15 20:44 UTC, erin2722 commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Discord]()
Sounds good! Just fixed!

2020-06-15 22:07 UTC, ivov commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Start](nodes-library/core-nodes/Start/README.md)
I think the link to the future Start node readme will be broken. This Discord readme will be in `docs/nodes/nodes-library/nodes/Discord/README.md`. To reach the future Start node readme in `docs/nodes-library/core-nodes/Start/README.md`, you would have to go back up to `nodes-library` and then down into `/core-nodes/Start/README.md`.

2020-06-15 22:16 UTC, ianjennings commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +Discord is a voice, video, and text communications platform for groups. Discord allows users to programatically send messages using webhooks.
Add link to discord.gg or whatever website.

2020-06-15 22:21 UTC, ianjennings requested changes

2020-06-15 22:21 UTC, ianjennings commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +4. Paste your webhook into the *Webhook URL* field of the Discord Node.
Maybe say 'on n8n"

2020-06-15 22:21 UTC, ianjennings commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +![GIF of Webhooks](https://media.giphy.com/media/WtI5wgNkgw0YoNqhfu/giphy.gif)
I usually default to putting these above instructions.

2020-06-15 22:21 UTC, ianjennings commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +This workflow allows you to send a message to a Discord channel using webhooks. You can also find the [workflow](https://n8n.io/integrations/n8n-nodes-base.discord) on this website. This example usag
This is generally how "call to actions" are structured:

```md
You can also [find the workflow on this website](https://n8n.io/integrations/n8n-nodes-base.discord).
```

2020-06-16 21:08 UTC, erin2722 commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Start](nodes-library/core-nodes/Start/README.md)
You're Right! Fixed it!

2020-06-17 01:50 UTC, ivov commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Start](../../core-nodes/Start)
That link points to a dir. I think it should be `(../../core-nodes/Start/README.md)`

2020-06-17 14:25 UTC, erin2722 commented on docs/nodes/nodes-library/nodes/Discord/README.md
> +- [Start](../../core-nodes/Start)
Same here, I the dir works as well as the file.

2020-06-18 08:41 UTC, merged