add google calender docs
MLH-Fellowship/n8n-docs pull request #19
Opened 2020-06-26 20:18 UTC by Shraddha2104

✨ Added Google Calender docs.
Let me know if any changes are needed!

2020-06-26 20:25 UTC, ivov requested changes
Looks good! Just small details.

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +# Google Calender
`Calendar`

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +# Google Calender
Same for all other instances below.

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +
Excess whitespace?

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +This workflow allows you to add an event to Google Calender. You can also find the [workflow](https://n8n.io/workflows/427) on the website. This example usage workflow would use the following two nod
`would use` → `uses`

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +This workflow allows you to add an event to Google Calender. You can also find the [workflow](https://n8n.io/workflows/427) on the website. This example usage workflow would use the following two nod
Maybe `allows you` → `shows you`?

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +2. To add a event to the calender, select the Event option under the *Resource* field.
`an event`

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +2. To add a event to the calender, select the Event option under the *Resource* field.
I think (not sure) it should be `*Event option*`. Please double check.

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +3. Select the Create option in the *Operation* field.
Italics for `Create option`?

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +5. Enter your start date of your event in the *Start* field.
`the start date`

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +6. Enter your end date of your event in the *End* field.
`the end date`

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +8. If you want to enter optional fields such as the attendees or location, etc as JSON data, then add those JSON parameters under the *Additional fields* field.
Optional fields should not be included in the instructions.

2020-06-26 20:25 UTC, ivov commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +
Extra whitespace?

2020-06-26 20:30 UTC, Shraddha2104 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +This workflow allows you to add an event to Google Calender. You can also find the [workflow](https://n8n.io/workflows/427) on the website. This example usage workflow would use the following two nod
your version is better, but the reference docs has `shows you`

2020-06-29 07:29 UTC, tanay1337 requested changes

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +permalink: /nodes/n8n-nodes-base.googleCalender
Calendar is misspelled in the document and in the folder name.

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +[Google Calender](https://www.google.com/calendar/) a time-management and scheduling calendar service developed by Google.
A minor grammatical error, missing 'is'.

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +    - Get an event
Could you please make sure that the operations occur in the same order as in the node. Also, the description should be the same as the text in the node.

<img width="241" alt="Screenshot 2020-06-29 at 09 04 43" src="https://user-images.githubusercontent.com/7481165/85983311-98c73f00-b9e7-11ea-8f3d-e70f1cea65fa.png">

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +2. To add an event to the calender, select *Event* under the *Resource* field.
This and the next step don't need to be mentioned as they are the default settings on the node.

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +7. Enable or disable *Use Default Reminder* field according to your needs.
We can skip the optional sections in the docs where there isn't a concrete instruction for the user to follow.

2020-06-29 07:29 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Calender/README.md
> +8. If you want to enter optional fields such as the attendees or location, etc as JSON data, then add those JSON parameters under the *Additional fields* field.
We can skip the optional sections in the docs where there isn't a concrete instruction for the user to follow.

2020-06-29 18:28 UTC, Shraddha2104 commented
Fixed docs according to @tanay1337's review !

2020-07-01 22:34 UTC, Shraddha2104 commented
Submitted to maintainers.

2020-07-01 22:34 UTC, closed without merging