Mailchimp docs
MLH-Fellowship/n8n-docs pull request #2
Opened 2020-06-12 21:30 UTC by erin2722

2020-06-15 12:56 UTC, ivov reviewed
A commit on Discord docs got mixed in here!

2020-06-15 13:31 UTC, ralph-dev approved these changes
LGTM

2020-06-15 20:38 UTC, erin2722 commented
Comment-- I accidentally merged in the discord docs to this branch but undid it with the most recent commit, so we are all good 👍

2020-06-15 22:15 UTC, ivov approved these changes

2020-06-15 22:17 UTC, ivov requested changes

2020-06-15 22:17 UTC, ivov commented on docs/nodes/nodes-library/nodes/Mailchimp/README.md
> +- [Mailchimp]()
We need to set the links as we did with Discord.

2020-06-17 01:52 UTC, ivov commented on docs/nodes/nodes-library/nodes/Mailchimp/README.md
> +- [Start](../../core-nodes/Start)
That link points to a dir. I think it should be `(../../core-nodes/Start/README.md)`

2020-06-17 14:24 UTC, erin2722 commented on docs/nodes/nodes-library/nodes/Mailchimp/README.md
> +- [Start](../../core-nodes/Start)
Both links work because like index, the dir automatically points to the readme.

2020-06-17 14:58 UTC, ivov commented on docs/nodes/nodes-library/nodes/Mailchimp/README.md
> +- [Start](../../core-nodes/Start)
I see, perfect then!

2020-06-18 16:41 UTC, merged