Google Tasks docs
MLH-Fellowship/n8n-docs pull request #20
Opened 2020-06-26 21:28 UTC by Shraddha2104

✨ Added Google Tasks docs.
Let me know if any changes are needed!

2020-06-29 07:33 UTC, tanay1337 requested changes

2020-06-29 07:33 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Tasks/README.md
> +[Google Tasks](https://www.google.com/tasks/) a task management service developed by Google.
The statement is missing an 'is'. Would be good to have a bit more information on the services, if possible.

2020-06-29 07:33 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Tasks/README.md
> +- Task
The indentation and descriptions need to be fixed here.

<img width="220" alt="Screenshot 2020-06-29 at 09 31 23" src="https://user-images.githubusercontent.com/7481165/85985648-4f78ee80-b9eb-11ea-99f9-dc021edb2db4.png">

2020-06-29 07:33 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Tasks/README.md
> +2. To add a new task to the tsklist, select *Task* under the *Resource* field.
This and the next step can be removed as the user does not need to take an action here.

2020-06-29 07:33 UTC, tanay1337 commented on docs/nodes/nodes-library/nodes/Google/Google Tasks/README.md
> +5. If you want to enter optional fields such as the attendees or location, etc as JSON data, then add those JSON parameters under the *Additional fields* field.
Optional steps can be removed from here.

2020-06-29 18:29 UTC, Shraddha2104 commented
Fixed docs according to @tanay1337's review

2020-07-01 22:35 UTC, Shraddha2104 commented
Submitted to maintainers.

2020-07-01 22:35 UTC, closed without merging