Spotify Documentation
MLH-Fellowship/n8n-docs pull request #25
Opened 2020-06-30 17:21 UTC by erin2722

🎵 Here is the Spotify Documentation for the new node!

2020-06-30 18:27 UTC, Shraddha2104 commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +   - Start Music
indentation a bit different

2020-06-30 18:27 UTC, Shraddha2104 commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +   - Get User's Playlist
indentation a bit different

2020-06-30 18:35 UTC, ivov commented on docs/nodes/credentials/Spotify/README.md
> +Create [Spotify Developer](https://developer.spotify.com/dashboard/login) account.
`Create a`

2020-06-30 18:35 UTC, ivov commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +    - Get
I would expand: `Get a Playlist`

2020-06-30 18:35 UTC, ivov commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +    - Get
I would expand: `Get a Track`

2020-06-30 18:35 UTC, ivov commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +- Spotify
I think the latest directive is that this has to be an empty link.

2020-07-06 14:14 UTC, ivov requested changes

2020-07-06 14:14 UTC, ivov commented on docs/nodes/nodes-library/nodes/Spotify/README.md
> +    - Get an Album's Tracks
Most docs under `Basic Operations` seem to use uppercase only for the first letter. This is unlike resource operation names in the codebase, where the casing is exactly as it is here. Please double check.

2020-07-06 15:19 UTC, ivov approved these changes

2020-07-07 15:36 UTC, ivov approved these changes

2020-07-20 19:14 UTC, ivov commented
Submitted and merged: https://github.com/n8n-io/n8n-docs/pull/15

2020-07-20 19:14 UTC, closed without merging